# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        product_thumbnails.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/product'
            public_url: '%env(DEFAULT_URI)%/uploads/product'

        project.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/project'
            public_url: '%env(DEFAULT_URI)%/uploads/project'

when@test:
    flysystem:
        storages:
            product_thumbnails.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/storage/test/product'
                public_url: '%env(DEFAULT_URI)%/uploads/product'

            project.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/storage/test/project'
                public_url: '%env(DEFAULT_URI)%/uploads/project'
