<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723123150 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CatalogSearch: pgvector extension + product_embedding table with HNSW cosine index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');
        $this->addSql('CREATE TABLE product_embedding (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, embedding vector(1536) NOT NULL, model VARCHAR(64) NOT NULL, source_thumbnail_hash VARCHAR(64) NOT NULL, embedded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_26FBE3234584665A ON product_embedding (product_id)');
        $this->addSql('ALTER TABLE product_embedding ADD CONSTRAINT FK_26FBE3234584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_product_embedding_hnsw ON product_embedding USING hnsw (embedding vector_cosine_ops)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_embedding DROP CONSTRAINT FK_26FBE3234584665A');
        $this->addSql('DROP TABLE product_embedding');
    }
}
