<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627151322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE category (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE product (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              external_id VARCHAR(255) DEFAULT NULL,
              title VARCHAR(255) NOT NULL,
              description VARCHAR(255) DEFAULT NULL,
              url VARCHAR(2048) NOT NULL,
              thumbnail_url VARCHAR(2048) NOT NULL,
              price DOUBLE PRECISION DEFAULT NULL,
              width_sm DOUBLE PRECISION DEFAULT NULL,
              height_sm DOUBLE PRECISION DEFAULT NULL,
              depth_sm DOUBLE PRECISION DEFAULT NULL,
              category_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              product
            ADD
              CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE product');
    }
}
