<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723164047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CatalogSearch: per-project product matches above the similarity threshold';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_product_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, match_score DOUBLE PRECISION NOT NULL, model VARCHAR(64) NOT NULL, matched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id UUID NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F96295F166D1F9C ON project_product_match (project_id)');
        $this->addSql('CREATE INDEX IDX_F96295F4584665A ON project_product_match (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_project_product_match ON project_product_match (project_id, product_id)');
        $this->addSql('ALTER TABLE project_product_match ADD CONSTRAINT FK_F96295F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_product_match ADD CONSTRAINT FK_F96295F4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_product_match DROP CONSTRAINT FK_F96295F166D1F9C');
        $this->addSql('ALTER TABLE project_product_match DROP CONSTRAINT FK_F96295F4584665A');
        $this->addSql('DROP TABLE project_product_match');
    }
}
