<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723192629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CatalogSearch: persisted per-project query embeddings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_embedding (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, embedding vector(1536) NOT NULL, model VARCHAR(64) NOT NULL, embedded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_59671079166D1F9C ON project_embedding (project_id)');
        $this->addSql('ALTER TABLE project_embedding ADD CONSTRAINT FK_59671079166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_embedding DROP CONSTRAINT FK_59671079166D1F9C');
        $this->addSql('DROP TABLE project_embedding');
    }
}
